version: '3.8'
services:
  locksmitha:
    build: .
    command: uvicorn src.locksmitha.main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keylindb
    ports:
      - "5432:5432"
